<!DOCTYPE html>

<html lang="fr">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>LDK VPN - Sécurité et confidentialité</title>

    <style>

        :root {

            --primary-color: #4a6bff;

            --secondary-color: #ff6b6b;

            --dark-bg: #1a1a2e;

            --dark-card: #16213e;

            --dark-text: #e6e6e6
